### ISSUE TITLE
Some questions about your excellent work in ICLR2023 "BETTER TEACHER BETTER STUDENT: DYNAMIC PRIOR KNOWLEDGE FOR KNOWLEDGE DISTILLATION"

### ISSUE THREAD

**Issue by cape-zck** [Cuibaby/HWLane#1]
Dear Qiu:
     Thank you for your excellent work "BETTER TEACHER BETTER STUDENT: DYNAMIC PRIOR KNOWLEDGE FOR KNOWLEDGE DISTILLATION" at ICLR2023, which I am currently studying. I have some questions about some details in the paper and would like to get your help.
    I have questions about the use of the "Encoder-Decoder" module in Vision Transformer in your paper. Because as far as I know, there is only the Transformer Encoder module in VIT, which is composed of several Encoder Blocks stacked repeatedly. What is the composition of the Decoder in your ICLR2023 work? Is this Decoder stacked by changing the number of channel numbers of the Encoder Blocks in Vision Transformer?
   I would appreciate it very much if you could offer me any help.

**Comment by Cuibaby** [comment]
Yes, you can refer to the MAE paper code for further information.
ref: Masked Autoencoders Are Scalable Vision Learners(https://arxiv.org/abs/2111.06377).

**Comment by cape-zck** [comment]
> Yes, you can refer to the MAE paper code for further information. ref: Masked Autoencoders Are Scalable Vision Learners(https://arxiv.org/abs/2111.06377).

Thank you very much for your reply! Your paper has inspired me a lot. Best Wishes!
